Repository gaelcolas/Sampler, pull requests merged in 2020-02, with the labels that each got.

#101 Support sending code coverage reports to Codecov.io
  .build/tasks/Common.Functions.ps1
  .build/tasks/Invoke-Pester.pester.build.ps1
  CHANGELOG.md
  Sampler/Assets/build.yaml.template
Labels: needs review

#118 Added warning messages to build tasks, while resolving project properties
  .build/tasks/Build-Module.ModuleBuilder.build.ps1
  .build/tasks/DeployAll.PSDeploy.build.ps1
  .build/tasks/DscResource.Test.build.ps1
  .build/tasks/Invoke-Pester.pester.build.ps1
  .build/tasks/New-Release.GitHub.build.ps1
  .build/tasks/generateHelp.PlatyPS.build.ps1
  .build/tasks/release.module.build.ps1
  CHANGELOG.md
Labels: needs review

#120 Enhancement: Build config file will now be dynamically determined
  CHANGELOG.md
  build.ps1
Labels: needs review

#117 Updated PesterScript to accept hashtables
  .build/tasks/Common.Functions.ps1
  .build/tasks/Invoke-Pester.pester.build.ps1
  CHANGELOG.md
  build.ps1
Labels: waiting for code fix

#124 Add conceptual help build task for DSC resources
  CHANGELOG.md
  Sampler/Assets/RequiredModules.psd1.template
  Sampler/Assets/build.yaml.template
Labels: needs review

#131 Default value of the parameter ModuleVersion always returns x.y.z-prerelease
  .build/tasks/Build-Module.ModuleBuilder.build.ps1
  .build/tasks/Common.Functions.psm1
  .build/tasks/DscResource.Test.build.ps1
  .build/tasks/Invoke-Pester.pester.build.ps1
  .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1
  .build/tasks/New-Release.GitHub.build.ps1
  .build/tasks/release.module.build.ps1
  CHANGELOG.md
  Sampler/Assets/azure-pipelines.simple.yml
  azure-pipelines.yml
Labels: ready for merge
